In [1]:
!pip install joblib

Requirement already satisfied: joblib in c:\users\hanso\anaconda3\envs\pythondata\lib\site-packages (0.17.0)

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import style
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
import numpy as np
import os
style.use("ggplot")
# Set the seed value for the notebook so the results are reproducible
from numpy.random import seed
seed(1)

# from matplotlib import rcParams
# rcParams['figure.figsize'] = 10, 8

In [3]:

# linear regression feature importance
from sklearn.datasets import make_regression
from sklearn.linear_model import LogisticRegression
from matplotlib import pyplot
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
import sklearn
import sklearn.datasets

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Read the CSV and Perform Basic Data Cleaning

In [4]:
df = pd.read_csv("all_data.csv")
# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')
# Drop the null rows
df = df.dropna()
df.head(100)

,Country,ISO_Code_x,2010_DR,2011_DR,2012_DR,2013_DR,2014_DR,2015_DR,2016_DR,2017_DR,...,2011_WAE,2012_WAE,2013_WAE,2014_WAE,2015_WAE,2016_WAE,2017_WAE,2018_WAE,2019_WAE,2020_WAE
0,Albania,ALB,54.0,53.5,53.0,52.6,52.1,51.6,51.1,50.6,...,22.0,22.0,22.0,22.0,22.0,22.0,22.0,22.0,22.0,22.0
1,Angola,AGO,99.7,99.3,102.0,105.0,108.0,111.0,114.0,117.0,...,46.3,46.3,46.3,46.3,46.3,46.3,46.3,46.3,46.3,46.3
2,Armenia,ARM,43.8,44.5,45.2,45.9,46.5,47.2,47.9,48.6,...,15.3,16.4,17.5,18.7,19.8,20.9,22.1,23.2,24.4,25.5
3,Azerbaijan,AZE,50.9,50.9,50.9,50.9,50.9,50.9,50.9,50.9,...,17.9,17.9,17.9,17.9,17.9,17.9,17.9,17.9,17.9,17.9
4,Bangladesh,BGD,68.5,67.8,66.3,64.9,63.4,61.8,60.2,58.5,...,7.1,19.3,31.6,43.8,56.0,68.3,80.5,92.7,105.0,117.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,Uzbekistan,UZB,51.0,49.3,47.6,46.0,44.3,42.7,41.0,39.3,...,19.0,19.0,19.0,19.0,19.0,19.0,19.0,19.0,19.0,19.0
68,Vietnam,VNM,48.9,48.8,48.8,48.7,48.6,48.5,48.5,48.4,...,55.0,54.3,53.6,52.9,52.2,51.5,50.8,50.1,49.4,48.7
69,Yemen,YEM,88.1,87.4,86.8,86.1,85.4,84.8,84.1,83.4,...,57.7,56.2,54.6,53.0,51.4,49.8,48.2,46.6,45.1,43.5
70,Zambia,ZMB,109.0,109.0,109.0,109.0,109.0,108.0,106.0,104.0,...,48.8,49.1,49.3,49.6,46.9,44.2,41.5,38.8,37.0,35.1
71,Zimbabwe,ZWE,89.3,88.3,88.8,89.3,89.7,90.2,90.0,89.8,...,20.6,19.3,17.9,16.5,15.1,14.4,13.7,13.0,12.3,11.5

In [5]:
df_drop_country_ISO=df.drop(['Country', 'ISO_Code_x'], axis=1)
df_drop_country_ISO

,2010_DR,2011_DR,2012_DR,2013_DR,2014_DR,2015_DR,2016_DR,2017_DR,2018_DR,2019_DR,...,2011_WAE,2012_WAE,2013_WAE,2014_WAE,2015_WAE,2016_WAE,2017_WAE,2018_WAE,2019_WAE,2020_WAE
0,54.0,53.5,53.0,52.6,52.1,51.6,51.1,50.6,50.1,49.6,...,22.0,22.0,22.0,22.0,22.0,22.0,22.0,22.0,22.0,22.0
1,99.7,99.3,102.0,105.0,108.0,111.0,114.0,117.0,119.0,122.0,...,46.3,46.3,46.3,46.3,46.3,46.3,46.3,46.3,46.3,46.3
2,43.8,44.5,45.2,45.9,46.5,47.2,47.9,48.6,49.3,50.0,...,15.3,16.4,17.5,18.7,19.8,20.9,22.1,23.2,24.4,25.5
3,50.9,50.9,50.9,50.9,50.9,50.9,50.9,50.9,50.9,50.9,...,17.9,17.9,17.9,17.9,17.9,17.9,17.9,17.9,17.9,17.9
4,68.5,67.8,66.3,64.9,63.4,61.8,60.2,58.5,56.9,55.3,...,7.1,19.3,31.6,43.8,56.0,68.3,80.5,92.7,105.0,117.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,51.0,49.3,47.6,46.0,44.3,42.7,41.0,39.3,37.7,36.0,...,19.0,19.0,19.0,19.0,19.0,19.0,19.0,19.0,19.0,19.0
68,48.9,48.8,48.8,48.7,48.6,48.5,48.5,48.4,48.3,48.2,...,55.0,54.3,53.6,52.9,52.2,51.5,50.8,50.1,49.4,48.7
69,88.1,87.4,86.8,86.1,85.4,84.8,84.1,83.4,82.7,82.1,...,57.7,56.2,54.6,53.0,51.4,49.8,48.2,46.6,45.1,43.5
70,109.0,109.0,109.0,109.0,109.0,108.0,106.0,104.0,102.0,100.0,...,48.8,49.1,49.3,49.6,46.9,44.2,41.5,38.8,37.0,35.1
71,89.3,88.3,88.8,89.3,89.7,90.2,90.0,89.8,89.5,89.3,...,20.6,19.3,17.9,16.5,15.1,14.4,13.7,13.0,12.3,11.5

In [6]:
country_disposition=df['GNI/C 2018'].values.reshape(-1,1)

data = country_disposition.copy()

# Select your features (columns)

In [7]:
# define dataset

X = df_drop_country_ISO
y= country_disposition

In [8]:
print (X)

    2010_DR  2011_DR  2012_DR  2013_DR  2014_DR  2015_DR  2016_DR  2017_DR  \
0      54.0     53.5     53.0     52.6     52.1     51.6     51.1     50.6
1      99.7     99.3    102.0    105.0    108.0    111.0    114.0    117.0
2      43.8     44.5     45.2     45.9     46.5     47.2     47.9     48.6
3      50.9     50.9     50.9     50.9     50.9     50.9     50.9     50.9
4      68.5     67.8     66.3     64.9     63.4     61.8     60.2     58.5
..      ...      ...      ...      ...      ...      ...      ...      ...
67     51.0     49.3     47.6     46.0     44.3     42.7     41.0     39.3
68     48.9     48.8     48.8     48.7     48.6     48.5     48.5     48.4
69     88.1     87.4     86.8     86.1     85.4     84.8     84.1     83.4
70    109.0    109.0    109.0    109.0    109.0    108.0    106.0    104.0
71     89.3     88.3     88.8     89.3     89.7     90.2     90.0     89.8

    2018_DR  2019_DR  ...  2011_WAE  2012_WAE  2013_WAE  2014_WAE  2015_WAE  \
0      50.1     49.6  ...      22.0      22.0      22.0      22.0      22.0
1     119.0    122.0  ...      46.3      46.3      46.3      46.3      46.3
2      49.3     50.0  ...      15.3      16.4      17.5      18.7      19.8
3      50.9     50.9  ...      17.9      17.9      17.9      17.9      17.9
4      56.9     55.3  ...       7.1      19.3      31.6      43.8      56.0
..      ...      ...  ...       ...       ...       ...       ...       ...
67     37.7     36.0  ...      19.0      19.0      19.0      19.0      19.0
68     48.3     48.2  ...      55.0      54.3      53.6      52.9      52.2
69     82.7     82.1  ...      57.7      56.2      54.6      53.0      51.4
70    102.0    100.0  ...      48.8      49.1      49.3      49.6      46.9
71     89.5     89.3  ...      20.6      19.3      17.9      16.5      15.1

    2016_WAE  2017_WAE  2018_WAE  2019_WAE  2020_WAE
0       22.0      22.0      22.0      22.0      22.0
1       46.3      46.3      46.3      46.3      46.3
2       20.9      22.1      23.2      24.4      25.5
3       17.9      17.9      17.9      17.9      17.9
4       68.3      80.5      92.7     105.0     117.0
..       ...       ...       ...       ...       ...
67      19.0      19.0      19.0      19.0      19.0
68      51.5      50.8      50.1      49.4      48.7
69      49.8      48.2      46.6      45.1      43.5
70      44.2      41.5      38.8      37.0      35.1
71      14.4      13.7      13.0      12.3      11.5

[72 rows x 161 columns]

# Create a Train Test Split

Use `koi_disposition` for the y values

In [9]:
#create train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)



X_scaler = StandardScaler().fit(X_train)
y_scaler=StandardScaler().fit(y_train)

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)



y_train_scaled =  y_scaler.transform(y_train)
y_test_scaled= y_scaler.transform(y_test)

In [10]:
X_train.head()

,2010_DR,2011_DR,2012_DR,2013_DR,2014_DR,2015_DR,2016_DR,2017_DR,2018_DR,2019_DR,...,2011_WAE,2012_WAE,2013_WAE,2014_WAE,2015_WAE,2016_WAE,2017_WAE,2018_WAE,2019_WAE,2020_WAE
33,67.0,66.1,65.1,64.0,62.9,61.9,60.8,59.7,58.6,57.5,...,2.48,2.74,2.46,2.18,1.89,1.61,1.33,1.27,1.21,1.14
39,96.5,95.1,93.7,92.3,91.0,89.6,88.2,86.8,85.4,84.0,...,77.70,81.20,84.60,88.10,91.60,95.00,98.50,102.00,105.00,109.00
59,108.0,105.0,102.0,99.3,96.1,92.9,89.6,86.4,89.8,93.1,...,51.90,51.30,50.80,52.20,53.50,54.90,56.30,57.60,59.00,60.40
16,84.5,84.7,83.9,83.1,82.3,81.5,80.7,79.9,79.1,78.3,...,52.30,55.00,57.60,60.20,62.80,65.40,68.10,70.70,73.30,75.90
35,91.7,90.6,89.4,88.2,87.0,85.8,84.6,83.5,82.3,81.1,...,35.50,35.60,35.70,35.70,35.80,35.80,35.90,35.90,36.00,36.10

# Pre-processing

Scale the data using the MinMaxScaler and perform some feature selection

In [11]:
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.layers import Dense

# Create a StandardScater model and fit it to the training data
X_scaler = StandardScaler().fit(X_train)

# Scale your data--this is done above, right?
# X_train_scaled=X_scaler.transform(X_train)
# X_test_scaled=X_scaler.transform(X_test)

from tensorflow import keras
from tensorflow.keras import layers

# Define Sequential model with 3 layers
model = keras.Sequential(
    [
        layers.Dense(163, activation="relu", name="layer1", input_dim=X.shape[1]),
        layers.Dense(100, activation="relu", name="layer2", input_dim=X.shape[1]),
        layers.Dense(50, activation="relu", name="layer3", input_dim=X.shape[1]),
        layers.Dense(25, activation="relu", name="layer4", input_dim=X.shape[1]),
        layers.Dense(1, activation= "softmax", name="layer5")
    ]
)


model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
layer1 (Dense)               (None, 163)               26406
_________________________________________________________________
layer2 (Dense)               (None, 100)               16400
_________________________________________________________________
layer3 (Dense)               (None, 50)                5050
_________________________________________________________________
layer4 (Dense)               (None, 25)                1275
_________________________________________________________________
layer5 (Dense)               (None, 1)                 26
=================================================================
Total params: 49,157
Trainable params: 49,157
Non-trainable params: 0
_________________________________________________________________

In [12]:
opt = keras.optimizers.Adam(learning_rate=0.01)
model.compile(loss='mse', optimizer=opt, metrics=['mae'])

In [13]:
print((X_train_scaled))
print((y_train_scaled))

[[-0.68484349 -0.70013376 -0.721613   ... -1.2646113  -1.2371006
  -1.2105514 ]
 [ 0.57637695  0.51337976  0.45720985 ...  3.37360427  3.46902051
   3.58521519]
 [ 1.06803915  0.92764817  0.79931578 ...  1.32916099  1.3832553
   1.42431906]
 ...
 [-1.22353425 -1.26922975 -1.17500641 ... -1.09884563 -1.06071741
  -1.02380729]
 [-1.17650569 -1.18553916 -1.1956152  ... -0.9533402  -0.9206084
  -0.88997401]
 [ 2.47889591  2.55961462  2.6128894  ... -1.02425107 -1.01718839
  -1.01091305]]
[[ 4.90345025e-01]
 [-8.79208394e-01]
 [-8.83797516e-01]
 [-1.28953570e-03]
 [-5.50387876e-01]
 [ 2.04023761e-01]
 [-8.73422111e-01]
 [ 1.64800076e+00]
 [ 1.29882848e+00]
 [-7.67273740e-01]
 [-8.27131844e-01]
 [-9.29090148e-01]
 [-6.28402938e-01]
 [ 1.84752777e+00]
 [-5.09684366e-01]
 [-8.62049071e-01]
 [-9.28092512e-01]
 [-8.16955966e-01]
 [-8.41497789e-01]
 [ 1.88144736e+00]
 [-9.99722710e-01]
 [-9.51836227e-01]
 [-8.19150763e-01]
 [-5.55974633e-01]
 [ 2.07216193e-01]
 [-4.97513218e-01]
 [-8.09772994e-01]
 [-1.23799122e-01]
 [-4.44638559e-01]
 [-6.75291787e-01]
 [ 3.12765983e-01]
 [ 1.34471970e+00]
 [-3.41483093e-01]
 [ 7.72675749e-01]
 [ 1.99118722e+00]
 [-4.64591261e-01]
 [ 3.81087358e+00]
 [-5.02700920e-01]
 [ 2.03225653e-01]
 [ 8.17137018e-02]
 [ 3.42495508e-01]
 [-5.12078690e-01]
 [ 3.60053885e-01]
 [-4.11916129e-01]
 [ 1.29999239e-01]
 [-5.09717620e-02]
 [-1.44549931e-01]
 [-8.18552182e-01]
 [ 6.91667781e-01]
 [-8.03787183e-01]
 [ 9.83575802e-01]
 [ 1.18709336e+00]
 [ 1.41455415e+00]
 [-9.77375685e-01]]

In [14]:
# # fit the model
# model.fit(X_train_scaled, y_train_scaled)
model.fit(
    X_train_scaled,
    y_train_scaled,
    epochs=100,
    shuffle=True,
    verbose=2
)

Epoch 1/100
2/2 - 1s - loss: 2.0000 - mae: 1.2750
Epoch 2/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 3/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 4/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 5/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 6/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 7/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 8/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 9/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 10/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 11/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 12/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 13/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 14/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 15/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 16/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 17/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 18/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 19/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 20/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 21/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 22/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 23/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 24/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 25/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 26/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 27/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 28/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 29/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 30/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 31/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 32/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 33/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 34/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 35/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 36/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 37/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 38/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 39/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 40/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 41/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 42/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 43/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 44/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 45/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 46/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 47/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 48/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 49/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 50/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 51/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 52/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 53/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 54/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 55/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 56/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 57/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 58/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 59/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 60/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 61/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 62/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 63/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 64/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 65/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 66/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 67/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 68/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 69/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 70/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 71/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 72/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 73/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 74/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 75/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 76/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 77/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 78/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 79/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 80/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 81/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 82/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 83/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 84/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 85/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 86/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 87/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 88/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 89/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 90/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 91/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 92/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 93/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 94/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 95/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 96/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 97/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 98/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 99/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750
Epoch 100/100
2/2 - 0s - loss: 2.0000 - mae: 1.2750

In [15]:
#test the model
model.evaluate(X_test_scaled, y_test_scaled)

1/1 [==============================] - 0s 384ms/step - loss: 2.2391 - mae: 1.3979

[2.239126205444336, 1.3978798389434814]

In [ ]:
# This model needs tuning. Roger sent some documentation in Slack to figure out 
# what kind of loss (SGD?) is best and how to tune the damn thing.

# Train the Model

In [16]:
print(f"Training Data Score: {model.evaluate(X_train_scaled, y_train_scaled)}")
print(f"Testing Data Score: {model.evaluate(X_test_scaled, y_test_scaled)}")

2/2 [==============================] - 0s 9ms/step - loss: 2.0000 - mae: 1.2750
Training Data Score: [2.0, 1.274971604347229]
1/1 [==============================] - 0s 70ms/step - loss: 2.2391 - mae: 1.3979
Testing Data Score: [2.239126205444336, 1.3978798389434814]

In [17]:
y_predict=model.predict(X_test_scaled)

output=y_scaler.inverse_transform(y_predict) #this is the predicted values unscaled. We compare them to the test outputs. Check that this
#syntax is correct--might need to update
sums=0
for n in range(0,len(output)):
    diff = y_test[n]-output[n]
    sums+=abs(diff)
    
diff=sums/len(output)

print(diff)

[7.00596813]

In [18]:
print (y)

[[12.3  ]
 [ 5.555]
 [ 9.277]
 [15.24 ]
 [ 4.057]
 [ 2.135]
 [ 6.849]
 [14.07 ]
 [ 1.705]
 [ 0.66 ]
 [ 3.597]
 [ 3.291]
 [ 0.777]
 [ 1.716]
 [12.9  ]
 [ 2.426]
 [ 5.804]
 [ 0.8  ]
 [ 3.589]
 [15.07 ]
 [10.74 ]
 [ 1.708]
 [ 9.359]
 [ 1.782]
 [15.79 ]
 [ 1.49 ]
 [ 4.099]
 [ 7.378]
 [ 2.211]
 [ 7.615]
 [ 1.665]
 [ 4.258]
 [ 6.829]
 [ 8.268]
 [22.17 ]
 [ 3.052]
 [ 3.317]
 [ 3.244]
 [ 1.04 ]
 [ 1.404]
 [ 1.159]
 [12.55 ]
 [ 1.965]
 [ 3.746]
 [ 6.833]
 [ 7.48 ]
 [ 1.154]
 [ 5.764]
 [ 9.683]
 [ 2.748]
 [ 4.79 ]
 [ 0.912]
 [ 5.086]
 [ 5.19 ]
 [ 3.686]
 [12.32 ]
 [ 1.959]
 [ 3.024]
 [ 3.256]
 [ 1.381]
 [11.76 ]
 [ 3.482]
 [ 2.805]
 [ 7.527]
 [ 1.593]
 [24.91 ]
 [ 1.752]
 [ 6.462]
 [ 6.22 ]
 [ 1.433]
 [ 3.582]
 [ 2.661]]

# Save the Model

In [19]:
# save your model by updating "your_name" with your name
# and "your_model" with your model variable
# be sure to turn this in to BCS
# if joblib fails to import, try running the command to install in terminal/git-bash
import joblib
filename = 'jmh_keras.sav'
# joblib.dump(model, filename)

model.save("models")

INFO:tensorflow:Assets written to: models\assets

In [20]:
#What does this need? Why is the "pickling" error showing up? Can this model be tuned like the Model_1 can? 
#Does GridSearch apply in this model?
model_loaded = keras.models.load_model("models")

In [21]:
model_loaded.evaluate(X_test_scaled, y_test_categorical)

NameError: name 'y_test_categorical' is not defined